/* global chrome, FocoCore */
const $=(id)=>document.getElementById(id);let state={},tick=null;const keys=["focusSession","dailyStats","dailyFocusGoalMinutes","blockingEnabled","userDomains"];
function send(message){return new Promise(resolve=>chrome.runtime.sendMessage(message,response=>resolve(response||{ok:false})));}
function message(text,ok=true){$("message").textContent=text;$("message").className=ok?"":"error";}
function clock(ms){const total=Math.max(0,Math.ceil(ms/1000));return String(Math.floor(total/60)).padStart(2,"0")+":"+String(total%60).padStart(2,"0");}
function activeSession(){const s=FocoCore.normalizeSession(state.focusSession);return s&&s.status==="active"&&!s.expired?s:null;}
function render(){const session=activeSession();$("idleState").hidden=!!session;$("runningState").hidden=!session;$("statusLabel").textContent=session?"Sessão protegida":"Pronto para começar";if(session){const remaining=session.endsAt-Date.now();$("timer").textContent=clock(remaining);$("activeIntention").textContent=session.intention||"Sessão de foco";$("activeMeta").textContent=(session.deepMode?"Modo profundo":"Pausas conscientes")+" · "+session.durationMin+" min";$("sessionProgress").style.width=Math.min(100,Math.max(0,((Date.now()-session.startedAt)/(session.endsAt-session.startedAt))*100))+"%";}const stats=FocoCore.normalizeDailyStats(state.dailyStats)[FocoCore.localDayKey()]||{};const focus=Math.round(stats.focusMinutes||0);const goal=FocoCore.clampInt(state.dailyFocusGoalMinutes,5,600,50);$("todayFocus").textContent=focus+" min";$("todayBlocks").textContent=stats.blockedAttempts||0;$("goalPercent").textContent=Math.min(100,Math.round(focus/goal*100))+"%";const protectedNow=state.blockingEnabled!==false||!!session;$("protectText").textContent=protectedNow?"Proteção ativa":"Proteção nas sessões";$("protectDot").className=protectedNow?"":"off";}
async function load(){state=await chrome.storage.local.get(keys);render();clearInterval(tick);tick=setInterval(()=>{render();if(state.focusSession&&!activeSession())void load();},1000);}
document.querySelectorAll("[data-min]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-min]").forEach(node=>node.classList.remove("active"));button.classList.add("active");$("duration").value=button.dataset.min;}));
$("quickSession").addEventListener("submit",async event=>{event.preventDefault();const intention=$("intention").value.trim();if(!intention)return message("Escreva uma intenção para começar.",false);const result=await send({type:"startFocusSession",payload:{intention,durationMin:$("duration").value,deepMode:true,sessionTabLimit:6}});if(!result.ok)return message("Já existe uma sessão ativa.",false);$("intention").value="";message("Sessão iniciada. Volte ao que importa.");await load();});
$("endSession").addEventListener("click",async()=>{if(!confirm("Encerrar a sessão antes do tempo?"))return;await send({type:"finishFocusSession",outcome:"abandoned"});message("Progresso salvo.");await load();});
$("openDashboard").addEventListener("click",()=>chrome.runtime.openOptionsPage());
$("addCurrent").addEventListener("click",async()=>{const tabs=await chrome.tabs.query({active:true,currentWindow:true});const host=FocoCore.normalizeHost(tabs[0]&&tabs[0].url);if(!host)return message("Esta página não pode ser adicionada.",false);const list=[...new Set([...(Array.isArray(state.userDomains)?state.userDomains:[]),host])].sort();await chrome.storage.local.set({userDomains:list});message(host+" adicionado às distrações.");});
chrome.storage.onChanged.addListener((_c,area)=>{if(area==="local")void load();});void load();
