/* global chrome, FocoCore */
const $=(id)=>document.getElementById(id);const params=new URLSearchParams(location.search);const host=FocoCore.normalizeHost(params.get("site"))||"site bloqueado";const reason=params.get("reason")==="adult"?"adult":"focus";let session=null;let reflectionTick=null;
function send(message){return new Promise(resolve=>chrome.runtime.sendMessage(message,response=>resolve(response||{ok:false})));}
function clock(ms){const total=Math.max(0,Math.ceil(ms/1000));return Math.floor(total/60)+":"+String(total%60).padStart(2,"0");}
async function init(){$("siteName").textContent=host;if(reason==="adult"){$("blockKicker").textContent="Proteção de conteúdo";$("blockTitle").textContent="Conteúdo adulto bloqueado";$("blockLead").textContent="A proteção contra conteúdo adulto está ativada neste navegador.";$("requestPause").hidden=true;$("insight").hidden=true;$("openDashboard").textContent="Abrir configurações de proteção";return;}const result=await send({type:"recordBlockedAttempt",host});if(result&&result.count)$("attemptCount").textContent=result.count+"ª";const data=await chrome.storage.local.get(["focusSession","dailyStats"]);session=FocoCore.normalizeSession(data.focusSession);const active=session&&session.status==="active"&&!session.expired;if(active){$("focusContext").hidden=false;$("focusIntention").textContent=session.intention||"Concluir esta sessão";$("sessionRemaining").textContent=clock(session.endsAt-Date.now())+" restantes";$("focusContext").querySelector("b").textContent=session.deepMode?"Modo profundo ativo":"Sessão protegida";if(session.deepMode){$("requestPause").disabled=true;$("requestPause").textContent="Acesso indisponível no modo profundo";}}const stats=FocoCore.normalizeDailyStats(data.dailyStats)[FocoCore.localDayKey()]||{};$("todayFocus").textContent=Math.round(stats.focusMinutes||0)+" min";}
$("goBack").addEventListener("click",()=>{if(history.length>1)history.back();else window.close();});
$("openDashboard").addEventListener("click",()=>{if(reason==="adult")location.href=chrome.runtime.getURL("ui/settings/settings.html");else chrome.runtime.openOptionsPage();});
$("requestPause").addEventListener("click",()=>{if(reason==="adult"||(session&&session.deepMode))return;$("requestPause").hidden=true;$("reflection").hidden=false;let seconds=10;$("reflectionTimer").textContent=seconds;reflectionTick=setInterval(()=>{seconds-=1;$("reflectionTimer").textContent=seconds;if(seconds<=0){clearInterval(reflectionTick);$("confirmPause").disabled=false;$("reflectionTimer").textContent="Agora você decide";}},1000);});
$("cancelPause").addEventListener("click",()=>{clearInterval(reflectionTick);$("reflection").hidden=true;$("requestPause").hidden=false;});
$("confirmPause").addEventListener("click",async()=>{if(reason==="adult")return;const result=await send({type:"grantMindfulAllowance",host,minutes:5});if(!result.ok)return;location.replace("https://"+host);});
void init();
